name: push to prod

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout git repos
      ##########################################################################

      # https://github.com/actions/checkout/tree/v4
      - name: ✔️ checkout dev.xo.fail static site
        uses: actions/checkout@v4
        with:
          token: '${{ secrets.PAT }}'
          repository: '${{ github.repository }}'
          ref: 'www-dev'
          path: 'www-dev'
          lfs: true
          show-progress: false
   
      # push to prod
      ##########################################################################

      - name: ⏩
        working-directory: www-dev
        run: |
          git push --force origin www-dev:www-prod
